<?php
/** @var \Keet\Form\Form\GenericDoctrineDeleteForm $form */
$getter = 'get' . ucfirst($form->getOption('unique_property'));
?>
    <h2>
        <?= $this->translate('Delete') ?>: <?= $form->getObject()->{$getter}() ?>
    </h2>
<?php
$form->prepare();
echo $this->form()
          ->openTag($form);
echo $this->formRow($form->get('csrf'));

echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('delete'));

echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag($form);